name: Semio's Notebook
description: Collection of My Thoughts
meta_description: "Blogging about Technologies, Stock Market/Trading."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://semio.github.io'
google_analytics: 'UA-4181755-4'

# Details for the RSS feed generator
url:            'http://semio.github.io'
author:         'Semio Z'
authorbio:      '小散一枚。新浪微博：<a href="http://weibo.com/s3mi0/" target="blank">@s3mi0</a>.'

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

kramdown:
  input: GFM
  enable_coderay: true
  coderay_line_numbers: nil
  coderay_tab_width: 4
  coderay_css: class

redcarpet:
  extensions: ["footnotes", "no_intra_emphasis", "tables", "strikethrough", "autolink"]
