name: Semio's Lab
description: Blogging about Stocks, Market and Trading.
meta_description: "Blogging about Stocks, Market and Trading."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://semio.github.io'
google_analytics: 'UA-4181755-4'

# Details for the RSS feed generator
url:            'http://semio.github.io'
author:         'Semio Z'
authorbio:      'Nerd. Love thinking, hacking stuffs. You can find me at <a href="http://weibo.com/s3mi0/" target="blank">@s3mi0</a>.'
